name: Create Mission Enclave Policy terraform plan

on:
  workflow_dispatch:
#  - pull_request

permissions:
  contents: read
  pull-requests: write

jobs:
  plan:
    runs-on: ubuntu-latest
    name: Policy terraform configuration
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      VM_PASSWORD: ${{ secrets.VM_PASSWORD }}
      ARM_ENVIRONMENT: ${{ secrets.ARM_ENVIRONMENT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: terraform plan
        uses: azurenoops/terraform-github-actions/terraform-plan@v1.34.2
        with:
          path: policy/terraform
          variables: |
            subscription_id_hub               = "${{ env.ARM_SUBSCRIPTION_ID }}"                     
          var_file: |
            policy/terraform/tfvars/parameters.tfvars
          backend_config: |
            storage_account_name=${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
            container_name=${{ secrets.AZURE_STORAGE_CONTAINER_NAME }}            
            resource_group_name=${{ secrets.TFSTATE_RG }}
          

  